default: clean compile sim

compile:
	source /tools/synopsys/vcs/P-2019.06-SP2/cshrc.vcs; \
	mkdir sim; \
	cd sim; \
    vcs +v2k -debug_all -f ../filelist -sverilog -full64; \
	cd ..

sim:
	pwd; \
	cd sim; \
	./simv

clean:
	rm -rf sim
